dataset:
    base_path: "/home/yaoyi/jang0124/sigspatial-cup/1026_pos_neg/"
    base_aug_path: "/home/yaoyi/shared/sigspatial/data_crop1024_shift512/"
    test_base_path : "/home/yaoyi/shared/sigspatial/data_crop1024_shift512/"
    dataset_name: "lake_crop"  
    #list of the dataset
    train_img_dir: ["/home/yaoyi/jang0124/sigspatial-cup/1026_pos_neg/pos/images",'/home/yaoyi/jang0124/sigspatial-cup/1026_pos_neg/neg/images']
    #  ['/home/yaoyi/shared/sigspatial/data_crop512_shift256/train_images/','/home/yaoyi/shared/sigspatial/data_crop512_shift256_aug/aug_train_images_img512/']
    train_mask_dir: ["/home/yaoyi/jang0124/sigspatial-cup/1026_pos_neg/pos/mask",'/home/yaoyi/jang0124/sigspatial-cup/1026_pos_neg/neg/mask']
    # ['/home/yaoyi/shared/sigspatial/data_crop512_shift256/train_mask','/home/yaoyi/shared/sigspatial/data_crop512_shift256_aug/aug_train_mask_img512']
    test_img_dir : ['/home/yaoyi/shared/sigspatial/data_crop1024_shift512/test_images']
    test_mask_dir : ['/home/yaoyi/shared/sigspatial/data_crop1024_shift512/test_mask']
    save_res_path : '/home/yaoyi/jang0124/sigspatial-cup/deeplabV3-PyTorch/experiments/prediction_test/'
    # test_pred_res_path : ''

image:
    out_stride: 16
    base_size: 1024
    crop_size: 1024
network:
    backbone: "resnet"  #choices=['resnet', 'xception', 'drn', 'mobilenet']
    sync_bn: false
    freeze_bn: false
    use_cuda: true
    num_classes: 2
training:
    workers: 4
    loss_type: 'ce'   #choices=['ce', 'focal']
    epochs: 20
    start_epoch: 0
    batch_size: 8
    use_balanced_weights: false
    lr: 0.0005
    lr_scheduler: "poly"     #choices=['poly', 'step', 'cos']
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: false
    callbacks:
    weights_initialization: 
        use_pretrained_weights: false
        restore_from: "./experiments/checkpoint_last.pth.tar"
    model_best_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_best.pth.tar"
        monitor: "val_loss"
    model_last_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_last.pth.tar"        
    train_on_subset: 
        enabled: false
        dataset_fraction: 0.1   
    output:
        output_weights: "./snapshots/checkpoint_best.pth.tar"
    tensorboard: 
        enabled: false
        log_dir: "./tensorboard/"
    no_val: false
    val_interval: 1
inference:
    batch_size: 2
gpu_ids: [0,1,2,3]
#seed: 1
#ft: false
#no_val: false
