dataset:
    region_txt_base_path : "./data_txt_folder/train_Greenland26X_22W_Sentinel2_2019-06-03_05_r2/"
    base_path: "./data/train_crop1024_shift512/"
    dataset_name: "lake_crop"  
    save_res_path : './data/experiments/prediction_results/'
model:
    weight: "./weight/final_weight.pth.tar"
image:
    out_stride: 16
    base_size: 1024
    crop_size: 1024
network:
    backbone: "resnet"  #choices=['resnet', 'xception', 'drn', 'mobilenet']
    sync_bn: false
    freeze_bn: false
    use_cuda: true
    num_classes: 2
training:
    workers: 4
    loss_type: 'dice'   #choices=['ce', 'focal']
    epochs: 14
    start_epoch: 0
    batch_size: 8
    use_balanced_weights: false
    lr: 0.0005
    lr_scheduler: "poly"     #choices=['poly', 'step', 'cos']
    momentum: 0.9
    weight_decay: 0.0005
    nesterov: false
    callbacks:
    weights_initialization: 
        use_pretrained_weights: false
        restore_from: "./experiments/checkpoint_last.pth.tar"
    output_dir : "./experiments/"
    model_best_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_best.pth.tar"
        monitor: "val_loss"
    model_last_checkpoint: 
        enabled: true
        out_file: "./experiments/checkpoint_last.pth.tar"        
    train_on_subset: 
        enabled: false
        dataset_fraction: 0.1   
    output:
        output_weights: "./snapshots/checkpoint_best.pth.tar"
    tensorboard: 
        enabled: false
        log_dir: "./tensorboard/"
    no_val: false
    val_interval: 1
inference:
    batch_size: 2
gpu_ids: [0,1,2,3]
#seed: 1
#ft: false
#no_val: false
