name: hugging
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - aiosignal=1.2.0
  - antlr-python-runtime=4.9.3
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.01.10
  - certifi=2020.6.20
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - commonmark=0.9.1
  - cython-blis=0.7.9
  - dataclasses=0.8
  - decorator=5.1.1
  - executing=0.8.3
  - gflags=2.2.2
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - huggingface_hub=0.15.1
  - hydra-core=1.3.2
  - icu=73.1
  - importlib_resources=6.0.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jsonlines=4.0.0
  - jupyter_client=6.1.12
  - jupyter_core=5.3.0
  - krb5=1.20.1
  - langcodes=3.3.0
  - ld_impl_linux-64=2.38
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.2.1
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.52.0
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libuuid=1.41.5
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.2
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.25.2
  - omegaconf=2.3.0
  - openssl=3.0.11
  - orc=1.7.4
  - parso=0.8.3
  - pathy=0.10.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.11
  - pytorch=1.13.1
  - re2=2022.04.01
  - readline=8.2
  - responses=0.13.3
  - rich=12.6.0
  - shellingham=1.5.3
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.1.9
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tk=8.6.12
  - typer=0.7.0
  - typing_extensions=4.7.1
  - tzdata=2023c
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - affine==2.4.0
    - aiohttp==3.8.5
    - async-timeout==4.0.2
    - attrs==22.1.0
    - blis==0.7.9
    - bottleneck==1.3.5
    - brotlipy==0.7.0
    - catalogue==2.0.9
    - cffi==1.15.1
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cmake==3.27.5
    - comm==0.1.2
    - confection==0.1.3
    - contourpy==1.1.1
    - cryptography==41.0.3
    - cycler==0.11.0
    - cymem==2.0.6
    - datasets==2.12.0
    - debugpy==1.6.7
    - dill==0.3.6
    - filelock==3.9.0
    - fiona==1.9.4.post1
    - fonttools==4.42.1
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - future==0.18.3
    - geopandas==0.14.0
    - huggingface-hub==0.15.1
    - idna==3.4
    - importlib-metadata==6.0.0
    - ipykernel==6.25.0
    - ipython==8.15.0
    - jedi==0.18.1
    - jupyter-core==5.3.0
    - kiwisolver==1.4.5
    - lit==16.0.6
    - markupsafe==2.1.1
    - matplotlib==3.8.0
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - monai==1.2.0
    - mpmath==1.3.0
    - multidict==6.0.2
    - multiprocess==0.70.14
    - murmurhash==1.0.7
    - networkx==3.1
    - numexpr==2.8.4
    - numpy==1.25.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - opencv-python==4.8.0.76
    - packaging==23.1
    - pandas==2.0.3
    - pillow==10.0.1
    - pip==23.2.1
    - platformdirs==3.10.0
    - preshed==3.0.6
    - prompt-toolkit==3.0.36
    - psutil==5.9.0
    - pyarrow==11.0.0
    - pydantic==1.10.8
    - pyopenssl==23.2.0
    - pyparsing==3.1.1
    - pyproj==3.6.1
    - pysocks==1.7.1
    - pytz==2022.7
    - pyyaml==6.0
    - pyzmq==25.1.0
    - rasterio==1.3.8
    - regex==2022.7.9
    - requests==2.31.0
    - safetensors==0.3.2
    - scipy==1.11.2
    - setuptools==68.0.0
    - shapely==2.0.1
    - snuggs==1.4.7
    - spacy==3.5.3
    - srsly==2.4.6
    - sympy==1.12
    - thinc==8.1.10
    - tokenizers==0.13.2
    - torch==2.0.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.7.1
    - transformers==4.32.1
    - triton==2.0.0
    - typing-extensions==4.7.1
    - urllib3==1.26.16
    - wasabi==1.1.2
    - wheel==0.38.4
    - xxhash==2.0.2
    - yarl==1.8.1
    - zipp==3.11.0
